apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server-pi
  namespace: minecraft
  labels:
    app: minecraft-server
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      volumes:
        - name: world
          persistentVolumeClaim:
            claimName: minecraft-world
      volumeMounts:
        - name: world
          mountPath: /app/cuberite/build-cuberite/Server/world
          subPath: world
        - name: world
          mountPath: /app/cuberite/build-cuberite/Server/world_nether
          subPath: world_nether
        - name: world
          mountPath: /app/cuberite/build-cuberite/Server/world_the_end
          subPath: world_the_end
        - name: world
          mountPath: /app/cuberite/build-cuberite/Server/players
          subPath: players
      containers:
        - name: minecraft-server
          image: joycelin79/cuberite
          tty: true
          imagePullPolicy: Always
          volumeMounts:
            - name: minecraft-data
              mountPath:  /data
          ports:
            - name: minecraft
              containerPort: 25565
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 1
              memory: 2Gi
          env:
            - name: EULA
              value: "TRUE"
            - name: MOTD
              value: MINECRAFT-ON-CPP-AND-K8S
          readinessProbe:
            exec:
              command:
              - mcstatus
              - 127.0.0.1
              - ping
            initialDelaySeconds: 30
            periodSeconds: 30
          livenessProbe:
            exec:
              command:
              - mcstatus
              - 127.0.0.1
              - ping
            initialDelaySeconds: 30
            periodSeconds: 30