apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server-pi
  annotations:
    kubesailEditorUid: 5d316a42-3174-4f33-ae7e-7c4c8476f95b
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      role: minecraft
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      volumes:
        - name: world
          persistentVolumeClaim:
            claimName: minecraft-world
      containers:
        - name: minecraft
          image: joycelin79/cuberite
          tty: true
          imagePullPolicy: Always
          volumeMounts:
            - name: world
              mountPath: /app/cuberite/build-cuberite/Server/world
              subPath: world
            - name: world
              mountPath: /app/cuberite/build-cuberite/Server/world_nether
              subPath: world_nether
            - name: world
              mountPath: /app/cuberite/build-cuberite/Server/world_the_end
              subPath: world_the_end
            - name: world
              mountPath: /app/cuberite/build-cuberite/Server/players
              subPath: players
          ports:
            - name: game-port
              containerPort: 25565
              hostPort: 25565
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 1
              memory: 2Gi
          env:
            - name: EULA
              value: "TRUE"
            - name: TYPE
              value: PAPER
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-world
  labels:
    app: minecraft
  annotations:
    kubesailEditorUid: d5a17d82-ee38-4ef3-9447-bfc3e68ceb26
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-router
  labels:
    app: minecraft
spec:
  ports:
  - port: 25565
    targetPort: 25565
  selector:
    app: minecraft