apiVersion: v1
kind: Service
metadata:
  name: minecraft-router
  namespace: minecraft
  labels:
    app: minecraft-router
spec:
  type: NodePort
  ports:
    - port: 25565
      nodePort: 30565
  selector:
    app: minecraft-sv