kind: Service
apiVersion: v1
metadata:
  name: minecraft-router
  namespace: minecraft
  labels:
    app: minecraft-router
spec:
  type: LoadBalancer
  selector:
    app: minecraft-sv
  ports:
    - name: minecraft-port
      protocol: TCP
      port: 25565
      targetPort: 25565