apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-world
  namespace: minecraft
  labels:
    app: minecraft-sv
  annotations:
    kubesailEditorUid: d5a17d82-ee38-4ef3-9447-bfc3e68ceb26
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi